"""V7 native S1-inspired search adapter. Leaves all vision/calibration untouched.

The *current* move and HOLD options are generated by the existing Python V5
collision-checked BFS; Rust evaluates five-ply futures and picks a root ID.
No keyboard/mouse input is generated. Standalone Rust executable required.
"""
from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
import subprocess
import time
from typing import Optional

import numpy as np
import solver_v5 as v5
from solver_v5 import RecommendationV5, describe_action_v5


@dataclass(frozen=True)
class SearchSettingsV7:
    depth: int = 5
    beam_width: int = 36
    time_budget_ms: float = 250.0
    max_current_states: int = 3000
    allow_hold: bool = True
    native_executable: str | None = None


def native_path(settings: SearchSettingsV7 | None = None) -> Path:
    explicit = (settings.native_executable if settings is not None else None) or os.environ.get('TRASSIST_V7_EXE')
    if explicit:
        return Path(explicit).expanduser().resolve()
    name = 'trassist-v7.exe' if os.name == 'nt' else 'trassist-v7'
    return Path(__file__).resolve().parent / 'native_v7' / 'target' / 'release' / name


def _serialize_root(root_id: int, move: v5._Move, hold_after: str | None, queue_index: int) -> str:
    rows = ','.join(f'{r:03x}' for r in move.board)
    spin = {'none': 'n', 'mini': 'm', 'full': 'f'}[move.spin]
    return f'{root_id} {rows} {move.lines} {spin} {hold_after or "-"} {queue_index}'


def make_request(roots, queue, settings: SearchSettingsV7, initial_b2b=0, initial_combo=-1):
    """Stable and testable Rust wire format (not JSON; no crate dependencies)."""
    if settings.depth < 1 or settings.beam_width < 1 or settings.time_budget_ms < 10:
        raise ValueError('Invalid search settings')
    if not roots:
        raise ValueError('At least one root move required')
    header = (f'V7 {"".join(queue) or "-"} {settings.depth} {settings.beam_width} '
              f'{int(settings.time_budget_ms)} {initial_b2b} {initial_combo} '
              f'{int(settings.allow_hold)} {len(roots)}')
    return header + ' ' + ' '.join(_serialize_root(i, move, new_hold, idx)
                                            for i, (move, _, new_hold, idx) in enumerate(roots)) + '\n'


def _legal_roots(board: np.ndarray, active, queue, hold, can_hold, settings):
    roots = []
    moves, visited = v5._current_locks(board, active, settings.max_current_states)
    roots.extend((m, False, hold, 0) for m in moves)
    if can_hold is True and settings.allow_hold:
        swap = hold if hold is not None else (queue[0] if queue else None)
        if swap is not None:
            spawned = v5._make_spawn(swap)
            if spawned is not None:
                alternate, states = v5._current_locks(board, spawned, settings.max_current_states)
                visited += states
                roots.extend((m, True, active.name, 0 if hold else 1) for m in alternate)
    return roots, visited


def find_best_v7(board: np.ndarray, active, next_queue=(), hold=None, can_hold=False,
                 settings: SearchSettingsV7 | None = None, *,
                 initial_b2b=0, initial_combo=-1) -> Optional[RecommendationV5]:
    """Choose a reachable CURRENT move using native future search.

    Raises FileNotFoundError when native binary is not built; no silent fallback
    to V6 (which could make benchmarking misleading). See README_V7.md.
    """
    settings = settings or SearchSettingsV7()
    if active.name not in v5.PIECES or (hold is not None and hold not in v5.PIECES):
        return None
    if board.shape != (20, 10):
        raise ValueError('Expected a 20x10 occupied-cell board')
    queue = tuple(p for p in next_queue if p in v5.PIECES)
    start = time.perf_counter()
    roots, visited = _legal_roots(board, active, queue, hold, can_hold, settings)
    if not roots:
        return None
    executable = native_path(settings)
    if not executable.is_file():
        raise FileNotFoundError(f'Native V7 engine not built: {executable}. Run cargo build --release in native_v7.')
    request = make_request(roots, queue, settings, initial_b2b, initial_combo)
    try:
        result = subprocess.run([str(executable)], input=request, text=True, capture_output=True,
                                timeout=max(2.0, (settings.time_budget_ms + 1500) / 1000),
                                check=True)
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError('Native solver timed out; lower beam_width or time_budget_ms') from exc
    output = result.stdout.strip().splitlines()
    if not output or not output[0].startswith('OK '):
        raise RuntimeError('V7 solver error: ' + (output[0] if output else result.stderr[:300]))
    fields = output[0].split()
    if len(fields) != 6:
        raise RuntimeError('Malformed native response: ' + output[0])
    _, root_id, score, depth, nodes, _engine_ms = fields
    root_id = int(root_id)
    if not 0 <= root_id < len(roots):
        raise RuntimeError('Native solver returned an invalid root ID')
    move, uses_hold, _, _ = roots[root_id]
    actions = (('HOLD',) if uses_hold else ()) + move.actions
    return RecommendationV5(move.name, move.r, move.x, move.y, move.cells,
                            float(score), move.lines, actions, visited, move.spin,
                            int(depth), int(nodes), (time.perf_counter()-start)*1000,
                            uses_hold, 0)


def describe_action_v7(active, best):
    return describe_action_v5(active, best)
